hostname r5
service integrated-vtysh-config
!
router ospf
 ospf router-id 5.5.5.5
 passive-interface default
 no passive-interface eth1
 no passive-interface eth2
 no passive-interface eth3
 network 10.0.15.0/30 area 0
 network 10.0.25.0/30 area 0
 network 10.0.45.0/30 area 0
 network 192.168.5.0/24 area 0
!
line vty
!